export default {
  en: {
    'homepage.title': 'Lithuanian ID Number Tool',
    'homepage.introHeader': 'What is it?',
    'homepage.introText': 'This tool checks and generates personal codes followingthe rules for creating a personal code of the Republic of Lithuania',
    'homepage.noticeHeader': 'Notice',
    'homepage.noticeText': [
      `This website is designed for educational and informational purposes only.
       The ID codes generated by the tool are supposed to be random, any resemblance to a real ID is unintended.`,
      `The site creator shall not be liable for any misuse or unauthorized use of the provided resources.`,
      `Data entered/generated on this site is not stored anywhere.`
    ],
    'homepage.entryPlaceholder': 'Personal ID Code',
    'button.check': 'Check',
    'button.generate': 'Generate',
    'error.header': 'Error',
    'error.wrongLength': 'Wrong format! The personal ID code consists of <strong>11</strong> digits.',
    'error.notNumber': 'Wrong format! The personal ID code consists of 11 <strong>digits</strong>.',
    'error.wrongCheckDigit': 'Wrong check digit (should be <strong>{{correctAnswer}}</strong>)!',
    'error.wrongFirstDigit': 'Wrong first digit! The first digit can range from 1 to 6 (odd for males, even for females)',
    'results.header': 'Decoding Results',
    'results.genderHeader': 'Gender',
    'results.birthDateHeader': 'Date of Birth',
    'results.birthOrderHeader': 'Previous Entry Count',
    'gender.male': 'Male',
    'gender.female': 'Female',
    'exception.month': 'Rare exception for elderly people who cannot recall their birth month, in such cases month is replaced with 0.',
    'exception.day': 'Rare exception for elderly people who cannot recall their birth date, in such cases day is replaced with 0.',

  },
  lt: {
    'homepage.title': 'Lietuvos asmens kodo įrankiai',
    'homepage.introHeader': 'Kas tai?',
    'homepage.introText': 'Šis įrankis tikrina ir generuoja asmens kodus pagal Lietuvos Respublikos asmens kodo sudarymo taisykles',
    'homepage.noticeHeader': 'Pastaba',
    'homepage.noticeText': [
      `Ši svetainė skirta tik edukaciniais ir informaciniais tikslais.
       Įrankio sugeneruoti Asmens kodai turėtų būti atsitiktiniai, bet koks panašumas į egzistuojantį a/k yra nenumatytas.`,
      `Svetainės kūrėjas neatsako už netinkamą ar neteisėtą pateiktų išteklių naudojimą.`,
      `Šioje svetainėje įvesti/sugeneruoti duomenys niekur nesaugomi.`
    ],
    'homepage.entryPlaceholder': 'Asmens kodas',
    'button.check': 'Tikrinti',
    'button.generate': 'Generuoti',
    'error.header': 'Klaida', 
    'error.wrongLength': 'Neteisingas formatas! Asmens kodas susideda iš <strong>11</strong> skaitmenų.',
    'error.notNumber': 'Neteisingas formatas! Asmens kodas susideda iš 11 <strong>skaitmenų</strong>.',
    'error.wrongCheckDigit': 'Neteisingas kontrolinis skaitmuo (turėtų būti <strong>{{correctAnswer}}</strong>)!',
    'error.wrongFirstDigit': 'Neteisingas pirmasis skaitmuo! Pirmasis skaitmuo gali būti nuo 1 iki 6 (nelyginiai vyrams, lyginiai moterims)',
    'results.header': 'A/k iššifravimo rezultatai',
    'results.genderHeader': 'Lytis',
    'results.birthDateHeader': 'Gimimo data',
    'results.birthOrderHeader': 'Tą dieną gimusių asmenų eilės numeris',
    'gender.male': 'Vyras',
    'gender.female': 'Moteris',
    'exception.month': 'Reta išimtis suteikiama vyresnio amžiaus žmonėms neprisimenantiems savo gimimo mėnesio. Tokiuose koduose vietoje mėnesio skaitmenų įrašomi 0.',
    'exception.day': 'Reta išimtis suteikiama vyresnio amžiaus žmonėms neprisimenantiems savo gimimo dienos. Tokiuose koduose vietoje dienos skaitmenų įrašomi 0.',

  }
}
